"""Postgres schema helpers for FinOps."""

from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

DEFAULT_DATABASE_URL = "postgresql://aop_dev:aop_dev_postgres_20260626@127.0.0.1:5432/aop"

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS finops_cost_records (
    cost_id       TEXT PRIMARY KEY,
    engine        TEXT NOT NULL,
    billing_mode  TEXT NOT NULL,
    tenant_id     TEXT NOT NULL,
    project_id    TEXT NOT NULL,
    issue_id      TEXT NOT NULL,
    agent_id      TEXT NOT NULL,
    runtime_id    TEXT NOT NULL,
    trace_id      TEXT,
    cost_usd      NUMERIC(18, 8) NOT NULL,
    usage_units   JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS finops_seat_usage (
    usage_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    seat_id         TEXT NOT NULL,
    vendor          TEXT NOT NULL,
    used_seconds    INTEGER NOT NULL,
    period_seconds  INTEGER NOT NULL,
    period_cost_usd NUMERIC(18, 8) NOT NULL,
    observed_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_finops_cost_project
    ON finops_cost_records(tenant_id, project_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_finops_cost_agent_runtime
    ON finops_cost_records(agent_id, runtime_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_finops_cost_trace
    ON finops_cost_records(trace_id);
CREATE INDEX IF NOT EXISTS idx_finops_seat_usage
    ON finops_seat_usage(tenant_id, seat_id, observed_at);
CREATE INDEX IF NOT EXISTS idx_finops_cost_project_agent
    ON finops_cost_records(tenant_id, project_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_finops_cost_project_runtime
    ON finops_cost_records(tenant_id, project_id, runtime_id);
CREATE INDEX IF NOT EXISTS idx_finops_cost_project_issue
    ON finops_cost_records(tenant_id, project_id, issue_id);
CREATE INDEX IF NOT EXISTS idx_finops_cost_project_model
    ON finops_cost_records(tenant_id, project_id, (metadata->>'model'));
CREATE INDEX IF NOT EXISTS idx_finops_cost_distinct_project
    ON finops_cost_records(tenant_id, project_id);
CREATE INDEX IF NOT EXISTS idx_finops_seat_usage_tenant_seat_vendor
    ON finops_seat_usage(tenant_id, seat_id, vendor);
"""


def _database_url(database_url: str | None = None) -> str:
    return database_url or os.environ.get("DATABASE_URL") or DEFAULT_DATABASE_URL


def _schema_name(name: str | None = None, *, seed: str | Path | None = None) -> str:
    if name:
        candidate = name
    elif os.environ.get("AOP_FINOPS_SCHEMA"):
        candidate = os.environ["AOP_FINOPS_SCHEMA"]
    else:
        source = str(seed or "aop_finops")
        candidate = "aop_finops_" + hashlib.sha256(source.encode("utf-8")).hexdigest()[:12]
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", candidate):
        raise ValueError(f"invalid Postgres schema name: {candidate!r}")
    return candidate


def connect(
    *,
    database_url: str | None = None,
    schema_name: str | None = None,
    schema_seed: str | Path | None = None,
) -> psycopg.Connection[Any]:
    """Open a Postgres connection with search_path set to the FinOps schema."""
    schema = _schema_name(schema_name, seed=schema_seed)
    conn = psycopg.connect(_database_url(database_url), row_factory=dict_row)
    with conn.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))
        cur.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
    conn.commit()
    return conn


def init_schema(conn: psycopg.Connection[Any]) -> None:
    """Create FinOps tables and indexes idempotently."""
    with conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
    conn.commit()
