"""Postgres connection and schema helpers for the agent registry."""

from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

DEFAULT_DATABASE_URL = "postgresql://aop_dev:aop_dev_postgres_20260626@127.0.0.1:5432/aop"

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS registry_agents (
    agent_id      TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    label         TEXT NOT NULL,
    vendor        TEXT NOT NULL,
    role          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active',
    workspace_id  TEXT,
    pane_id       TEXT,
    stable_key    TEXT NOT NULL,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at    TIMESTAMPTZ,
    UNIQUE (tenant_id, stable_key)
);

CREATE TABLE IF NOT EXISTS registry_pane_mappings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      TEXT NOT NULL REFERENCES registry_agents(agent_id),
    workspace_id  TEXT NOT NULL,
    pane_id       TEXT NOT NULL,
    session_id    TEXT,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    observed_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retired_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_registry_agents_tenant_status
    ON registry_agents(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_registry_agents_current_pane
    ON registry_agents(workspace_id, pane_id);
CREATE INDEX IF NOT EXISTS idx_registry_pane_mappings_agent
    ON registry_pane_mappings(agent_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_registry_agents_tenant_status_created
    ON registry_agents(tenant_id, status, created_at ASC, agent_id ASC);
CREATE INDEX IF NOT EXISTS idx_registry_agents_active_current_pane
    ON registry_agents(workspace_id, pane_id)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_registry_pane_mappings_agent_observed
    ON registry_pane_mappings(agent_id, observed_at ASC, id ASC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_registry_active_pane
    ON registry_pane_mappings(workspace_id, pane_id)
    WHERE retired_at IS NULL;
"""


def _database_url(database_url: str | None = None) -> str:
    return database_url or os.environ.get("DATABASE_URL") or DEFAULT_DATABASE_URL


def _schema_name(name: str | None = None, *, seed: str | Path | None = None) -> str:
    if name:
        candidate = name
    elif os.environ.get("AOP_REGISTRY_SCHEMA"):
        candidate = os.environ["AOP_REGISTRY_SCHEMA"]
    else:
        source = str(seed or "aop_registry")
        candidate = "aop_registry_" + hashlib.sha256(source.encode("utf-8")).hexdigest()[:12]
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", candidate):
        raise ValueError(f"invalid Postgres schema name: {candidate!r}")
    return candidate


def connect(
    *,
    database_url: str | None = None,
    schema_name: str | None = None,
    schema_seed: str | Path | None = None,
) -> psycopg.Connection[Any]:
    """Open a Postgres connection with search_path set to the registry schema."""
    schema = _schema_name(schema_name, seed=schema_seed)
    conn = psycopg.connect(_database_url(database_url), row_factory=dict_row)
    with conn.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))
        cur.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema)))
    conn.commit()
    return conn


def init_schema(conn: psycopg.Connection[Any]) -> None:
    """Create the registry schema idempotently on an open connection."""
    with conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
    conn.commit()
