"""Postgres schema and connection helpers for HerdMaster."""

from __future__ import annotations

import logging
import os
import re
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

try:
    from psycopg_pool import ConnectionPool
except ImportError:  # pragma: no cover — pool is optional
    ConnectionPool = None  # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 2

DEFAULT_DATABASE_URL = "postgresql://aop_dev:aop_dev_postgres_20260626@aop-postgres:5432/aop"
DEFAULT_SCHEMA_NAME = "hm_main"

AGENT_FK_POLICIES = {
    ("health_events", "agent_id"): "CASCADE",
    ("tasks", "assigned_to"): "SET NULL",
    ("tasks", "created_by"): "SET NULL",
    ("tasks", "completed_by"): "SET NULL",
    ("task_audit_log", "agent_id"): "SET NULL",
    ("messages", "from_agent"): "SET NULL",
}

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS agents (
    id                 TEXT PRIMARY KEY,
    label              TEXT NOT NULL,
    type               TEXT NOT NULL,
    role               TEXT NOT NULL,
    herdr_pane         TEXT,
    herdr_ws           TEXT,
    state              TEXT DEFAULT 'unknown',
    health             TEXT DEFAULT 'healthy',
    strengths          TEXT,
    avg_task_seconds   INTEGER,
    tasks_completed    INTEGER DEFAULT 0,
    last_heartbeat     TIMESTAMPTZ,
    last_output_hash   TEXT,
    created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id                     TEXT PRIMARY KEY,
    name                   TEXT NOT NULL,
    scope                  TEXT NOT NULL,
    state                  TEXT DEFAULT 'submitted',
    complexity_tier        TEXT,
    deadline               TIMESTAMPTZ,
    squad_recommendation   TEXT,
    squad_approved         TEXT,
    eta_optimistic_hours   DOUBLE PRECISION,
    eta_expected_hours     DOUBLE PRECISION,
    eta_pessimistic_hours  DOUBLE PRECISION,
    eta_rationale          TEXT,
    orchestrator_analysis  TEXT,
    human_decision         TEXT,
    human_notes            TEXT,
    total_tasks            INTEGER DEFAULT 0,
    completed_tasks        INTEGER DEFAULT 0,
    failed_tasks           INTEGER DEFAULT 0,
    created_by             TEXT,
    approved_at            TIMESTAMPTZ,
    completed_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id                 TEXT PRIMARY KEY,
    project_id         TEXT REFERENCES projects(id),
    title              TEXT NOT NULL,
    description        TEXT,
    prompt             TEXT NOT NULL,
    state              TEXT DEFAULT 'queued',
    blocked_reason     TEXT,
    priority           INTEGER DEFAULT 2,
    assigned_to        TEXT REFERENCES agents(id) ON DELETE SET NULL,
    depends_on         TEXT,
    created_by         TEXT REFERENCES agents(id) ON DELETE SET NULL,
    dispatched_at      TIMESTAMPTZ,
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    completed_by       TEXT REFERENCES agents(id) ON DELETE SET NULL,
    evidence           TEXT,
    duration_seconds   INTEGER,
    error_message      TEXT,
    retry_count        INTEGER DEFAULT 0,
    max_retries        INTEGER DEFAULT 3,
    timeout_seconds    INTEGER DEFAULT 1800,
    estimate_minutes   INTEGER,
    subtasks           TEXT,
    progress           TEXT,
    acceptance_criteria TEXT,
    created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    version            INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS task_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT NOT NULL REFERENCES tasks(id),
    agent_id    TEXT REFERENCES agents(id) ON DELETE SET NULL,
    event       TEXT NOT NULL,
    timestamp   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    evidence    TEXT,
    notes       TEXT
);

CREATE TABLE IF NOT EXISTS task_alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT REFERENCES tasks(id),
    agent_id    TEXT REFERENCES agents(id) ON DELETE SET NULL,
    alert_type  TEXT NOT NULL,
    message     TEXT NOT NULL,
    active      BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (task_id, agent_id, alert_type)
);

CREATE TABLE IF NOT EXISTS messages (
    id              TEXT PRIMARY KEY,
    type            TEXT NOT NULL,
    from_agent      TEXT REFERENCES agents(id) ON DELETE SET NULL,
    to_agent        TEXT,
    correlation_id  TEXT,
    payload         TEXT NOT NULL,
    delivered       BOOLEAN DEFAULT FALSE,
    acknowledged    BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS health_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    TEXT REFERENCES agents(id) ON DELETE CASCADE,
    event_type  TEXT NOT NULL,
    details     TEXT,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       TEXT REFERENCES projects(id),
    complexity_tier  TEXT,
    total_tasks      INTEGER,
    agents_used      INTEGER,
    estimated_hours  DOUBLE PRECISION,
    actual_hours     DOUBLE PRECISION,
    accuracy_pct     DOUBLE PRECISION,
    completed_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_state ON tasks(state);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority, state);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_messages_to ON messages(to_agent, delivered);
CREATE INDEX IF NOT EXISTS idx_health_agent ON health_events(agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_projects_state ON projects(state);
CREATE INDEX IF NOT EXISTS idx_project_history_complexity ON project_history(complexity_tier);
CREATE INDEX IF NOT EXISTS idx_audit_task ON task_audit_log(task_id);
CREATE INDEX IF NOT EXISTS idx_audit_agent ON task_audit_log(agent_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_task_alerts_type ON task_alerts(alert_type, active);
CREATE INDEX IF NOT EXISTS idx_task_alerts_task ON task_alerts(task_id);
"""

SCHEMA_SQL = POSTGRES_SCHEMA_SQL


class PgCursor:
    """Small DB-API compatibility wrapper around a psycopg cursor."""

    def __init__(self, cursor: psycopg.Cursor[Any]) -> None:
        self._cursor = cursor

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self) -> int | None:
        row = self.fetchone()
        if row is None:
            return None
        if isinstance(row, dict):
            return int(row.get("id")) if row.get("id") is not None else None
        return int(row[0])

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return list(self._cursor.fetchall())

    def __iter__(self):
        return iter(self._cursor)


class PgConnection:
    """Connection facade preserving the subset of the DB API used by HerdMaster.

    DECISION: Add safe_execute wrapper with automatic rollback on error
    SOURCE:   https://www.psycopg.org/psycopg3/docs/basic/transactions.html
    REF:      "Transaction contexts" — rollback on exception exit
    RATIONALE: Prevent connection from staying in aborted transaction state
              which blocks all subsequent SQL until explicit rollback.
    VERSION:  psycopg 3.3.x
    """

    def __init__(self, conn: psycopg.Connection[Any], schema_name: str) -> None:
        self._conn = conn
        self.schema_name = schema_name
        self._set_search_path()

    def _set_search_path(self) -> None:
        with self._conn.cursor() as cur:
            cur.execute(
                sql.SQL("SET search_path TO {}, public").format(sql.Identifier(self.schema_name))
            )
        self._conn.commit()

    def execute(self, query: str, params: Any = None) -> PgCursor:
        try:
            cur = self._conn.cursor()
            cur.execute(_translate_placeholders(query), params)
            return PgCursor(cur)
        except Exception:
            # Auto-rollback on failure to prevent the connection from staying
            # in psycopg's InFailedTransaction state, which would cause all
            # subsequent SQL to fail with "current transaction is aborted".
            # Only attempt when pgconn reports INERROR.  When inside a
            # psycopg3 ``with conn.transaction():`` context, explicit
            # rollback raises ProgrammingError — that is safe to ignore
            # because the context manager handles rollback on exit.
            try:
                from psycopg.pq import TransactionStatus
                if self._conn.pgconn.transaction_status == TransactionStatus.INERROR:
                    self.rollback()
            except Exception as rb_exc:
                # Suppress "Explicit rollback() forbidden within a
                # Transaction context" — psycopg3 handles this for us.
                if "Transaction context" not in str(rb_exc):
                    logger.warning("rollback after execute failure also failed", exc_info=True)
            raise

    def safe_execute(self, query: str, params: Any = None) -> PgCursor:
        """Execute SQL with automatic rollback on error.

        If the query fails, conn.rollback() is called before re-raising
        so the connection does not remain in an aborted transaction state.
        """
        try:
            return self.execute(query, params)
        except Exception:
            self.rollback()
            raise

    def commit(self) -> None:
        self._conn.commit()
        self._set_search_path()

    def rollback(self) -> None:
        self._conn.rollback()
        try:
            self._set_search_path()
        except Exception:
            # _set_search_path() may fail if called inside a psycopg3
            # Transaction context or if the connection is in a bad state.
            # The rollback itself succeeded, so this is non-fatal.
            pass

    @contextmanager
    def transaction(self) -> Iterator["PgConnection"]:
        """Run a block in a psycopg transaction context.

        psycopg commits on normal exit and rolls back on exception exit.  The
        search_path is restored afterwards because rollback can discard session
        state established inside the transaction.
        """
        try:
            with self._conn.transaction():
                yield self
        finally:
            self._set_search_path()

    def close(self) -> None:
        self._conn.close()


def _translate_placeholders(query: str) -> str:
    return query.replace("?", "%s")


def _schema_from_path(db_path: str | Path | None) -> str:
    return os.environ.get("HERDMASTER_DB_SCHEMA", DEFAULT_SCHEMA_NAME)


def _normalize_schema_name(schema_name: str) -> str:
    schema_name = schema_name.strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", schema_name):
        raise ValueError(f"invalid Postgres schema name: {schema_name!r}")
    return schema_name


def _database_url(db_path: str | Path | None, database_url: str | None) -> str:
    if database_url:
        return database_url
    if db_path is not None and str(db_path).startswith(("postgresql://", "postgres://")):
        return str(db_path)
    return os.environ.get("DATABASE_URL") or DEFAULT_DATABASE_URL


def connect(
    db_path: str | Path | None = None,
    *,
    database_url: str | None = None,
    schema_name: str | None = None,
) -> PgConnection:
    """Open a Postgres connection for HerdMaster.

    ``db_path`` is retained for call-site compatibility. When it is not a
    Postgres URL, it is used only to derive an isolated schema name for tests.
    Runtime connections use ``DATABASE_URL`` or the local AOP Postgres default.
    """
    schema = _normalize_schema_name(schema_name or _schema_from_path(db_path))
    conn = psycopg.connect(_database_url(db_path, database_url), row_factory=dict_row)
    return PgConnection(conn, schema)


# ---------------------------------------------------------------------------
# Connection pool helpers (R2 — psycopg_pool)
# ---------------------------------------------------------------------------

def _pool_reset(conn: psycopg.Connection[Any]) -> None:
    """Reset callback invoked when a connection is returned to the pool.

    DECISION: Reset search_path and DISCARD TEMP to clear session state
    SOURCE:   https://www.psycopg.org/psycopg3/docs/advanced/pool.html
    REF:      "Connections life cycle" → reset callback
    RATIONALE: Ensures returned connections have clean state for next consumer.
    VERSION:  psycopg_pool 3.2.x
    """
    try:
        conn.execute("DISCARD TEMP")
        conn.execute("RESET ALL")
    except Exception:
        logger.warning("pool reset callback failed; connection will be discarded", exc_info=True)
        raise


def _pool_reconnect_failed(pool: Any) -> None:
    """Callback invoked when the pool exhausts reconnect_timeout.

    DECISION: Log critical error; do NOT call sys.exit() so orchestrator can decide
    SOURCE:   https://www.psycopg.org/psycopg3/docs/advanced/pool.html
    REF:      "Pool connection and sizing" → reconnect_failed callback
    RATIONALE: Alerting via logging; Kubernetes/systemd liveness probes handle restart.
    VERSION:  psycopg_pool 3.2.x
    """
    logger.critical(
        "DB connection pool reconnect FAILED after timeout — pool stats: %s",
        pool.get_stats() if hasattr(pool, "get_stats") else "unavailable",
    )


def connect_pool(
    conninfo: str | None = None,
    *,
    min_size: int = 2,
    max_size: int = 10,
    max_idle: float = 300.0,
    max_lifetime: float = 3600.0,
    reconnect_timeout: float = 300.0,
    timeout: float = 30.0,
    schema_name: str | None = None,
    open: bool = True,
    wait: bool = True,
    wait_timeout: float = 30.0,
    kwargs: dict[str, Any] | None = None,
) -> "ConnectionPool":
    """Create a psycopg ConnectionPool with robustness callbacks.

    DECISION: Use ConnectionPool.check_connection as the check callback
    SOURCE:   https://www.psycopg.org/psycopg3/docs/api/pool.html
    REF:      ConnectionPool constructor — check parameter
    RATIONALE: check_connection pings the server; broken connections are
              detected and replaced before being handed to the caller.
    VERSION:  psycopg_pool 3.2.x

    Returns the pool object.  The caller is responsible for closing it.
    """
    if ConnectionPool is None:
        raise ImportError(
            "psycopg_pool is required for connection pooling. "
            "Install with: pip install 'psycopg[pool]'"
        )

    conninfo = conninfo or os.environ.get("DATABASE_URL") or DEFAULT_DATABASE_URL
    extra_kwargs: dict[str, Any] = {"row_factory": dict_row}
    if kwargs:
        extra_kwargs.update(kwargs)

    schema = _normalize_schema_name(
        schema_name or os.environ.get("HERDMASTER_DB_SCHEMA", DEFAULT_SCHEMA_NAME)
    )

    def _configure(conn: psycopg.Connection[Any]) -> None:
        """Set search_path on every freshly-created connection."""
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema))
            )

    pool = ConnectionPool(
        conninfo=conninfo,
        min_size=min_size,
        max_size=max_size,
        max_idle=max_idle,
        max_lifetime=max_lifetime,
        reconnect_timeout=reconnect_timeout,
        timeout=timeout,
        open=open,
        check=ConnectionPool.check_connection,
        reset=_pool_reset,
        reconnect_failed=_pool_reconnect_failed,
        configure=_configure,
        kwargs=extra_kwargs,
    )

    if open and wait:
        pool.wait(timeout=wait_timeout)
        logger.info(
            "HerdMaster connection pool ready — stats: %s",
            pool.get_stats(),
        )

    return pool


def pool_get_stats(pool: Any) -> dict[str, Any]:
    """Return pool statistics suitable for Prometheus export.

    DECISION: Expose get_stats() counters for monitoring
    SOURCE:   https://www.psycopg.org/psycopg3/docs/api/pool.html
    REF:      ConnectionPool.get_stats()
    RATIONALE: Surfaces pool_size, pool_available, requests_waiting,
              connections_lost, returns_bad, etc. for alerting.
    VERSION:  psycopg_pool 3.2.x
    """
    if hasattr(pool, "get_stats"):
        return dict(pool.get_stats())
    return {}


def init_db(conn: PgConnection) -> None:
    """Create the HerdMaster Postgres schema and indexes idempotently."""
    with conn._conn.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(conn.schema_name)))
    conn.commit()
    # Split POSTGRES_SCHEMA_SQL by semicolons to execute each statement individually.
    # This avoids psycopg3 prepared statement errors with multi-statement queries.
    for statement in POSTGRES_SCHEMA_SQL.split(";"):
        stmt = statement.strip()
        if stmt:
            conn.execute(stmt)
    conn.commit()
    migrate_ottl_columns(conn)
    migrate_all_agent_foreign_keys(conn)
    cleanup_orphan_hm_schemas(conn)


def migrate_ottl_columns(conn: PgConnection) -> None:
    """Apply idempotent OTTL task lifecycle schema extensions."""
    statements = [
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimate_minutes INTEGER",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS subtasks TEXT",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS progress TEXT",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS acceptance_criteria TEXT",
    ]
    with conn._conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
    conn.commit()


def migrate_all_agent_foreign_keys(conn: PgConnection) -> list[str]:
    """Migrate agent foreign keys in every HerdMaster schema currently present."""
    schemas = [conn.schema_name]
    with conn._conn.cursor() as cur:
        cur.execute(
            """
            SELECT schema_name
            FROM information_schema.schemata
            WHERE schema_name LIKE 'hm\\_%%' ESCAPE '\\'
            ORDER BY schema_name
            """
        )
        for row in cur.fetchall():
            schema_name = str(row["schema_name"])
            if schema_name not in schemas:
                schemas.append(schema_name)

    migrated: list[str] = []
    for schema_name in schemas:
        if _schema_has_table(conn, schema_name, "agents"):
            migrate_agent_foreign_keys(conn, schema_name)
            migrated.append(schema_name)
    return migrated


def migrate_agent_foreign_keys(conn: PgConnection, schema_name: str | None = None) -> None:
    """Force all FKs that reference agents(id) to their expected delete rules."""
    target_schema = _normalize_schema_name(schema_name or conn.schema_name)
    with conn._conn.cursor() as cur:
        for (table_name, column_name), delete_rule in AGENT_FK_POLICIES.items():
            constraint_name = f"{table_name}_{column_name}_fkey"
            cur.execute(
                """
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_schema = kcu.constraint_schema
                 AND tc.constraint_name = kcu.constraint_name
                JOIN information_schema.constraint_column_usage ccu
                  ON ccu.constraint_schema = tc.constraint_schema
                 AND ccu.constraint_name = tc.constraint_name
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_schema = %s
                  AND tc.table_name = %s
                  AND kcu.column_name = %s
                  AND ccu.table_schema = %s
                  AND ccu.table_name = 'agents'
                  AND ccu.column_name = 'id'
                """,
                (target_schema, table_name, column_name, target_schema),
            )
            for row in cur.fetchall():
                cur.execute(
                    sql.SQL("ALTER TABLE {}.{} DROP CONSTRAINT {}").format(
                        sql.Identifier(target_schema),
                        sql.Identifier(table_name),
                        sql.Identifier(str(row["constraint_name"])),
                    )
                )
            cur.execute(
                sql.SQL(
                    "ALTER TABLE {}.{} ADD CONSTRAINT {} "
                    "FOREIGN KEY ({}) REFERENCES {}.agents(id) ON DELETE "
                ).format(
                    sql.Identifier(target_schema),
                    sql.Identifier(table_name),
                    sql.Identifier(constraint_name),
                    sql.Identifier(column_name),
                    sql.Identifier(target_schema),
                )
                + sql.SQL(delete_rule)
            )
    conn.commit()


def _schema_has_table(conn: PgConnection, schema_name: str, table_name: str) -> bool:
    with conn._conn.cursor() as cur:
        cur.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = %s AND table_name = %s
            """,
            (schema_name, table_name),
        )
        return cur.fetchone() is not None


def cleanup_orphan_hm_schemas(conn: PgConnection, active_schema: str | None = None) -> list[str]:
    """Drop orphan HerdMaster hash schemas, preserving the active fixed schema."""
    keep = _normalize_schema_name(active_schema or conn.schema_name)
    dropped: list[str] = []
    with conn._conn.cursor() as cur:
        cur.execute(
            """
            SELECT schema_name
            FROM information_schema.schemata
            WHERE schema_name LIKE 'hm\\_%%' ESCAPE '\\'
              AND schema_name <> %s
            ORDER BY schema_name
            """,
            (keep,),
        )
        for row in cur.fetchall():
            schema_name = str(row["schema_name"])
            cur.execute(sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(schema_name)))
            dropped.append(schema_name)
    conn.commit()
    return dropped
